// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI-powered portfolio review tool.
 *
 * - reviewPortfolio - A function that handles the portfolio review process.
 * - PortfolioReviewInput - The input type for the reviewPortfolio function.
 * - PortfolioReviewOutput - The return type for the reviewPortfolio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PortfolioReviewInputSchema = z.object({
  portfolioContent: z
    .string()
    .describe('The content of the portfolio to be reviewed.'),
  userGoals: z
    .string()
    .describe('The user goals for the portfolio (e.g., job search, freelance work).'),
  targetAudience: z
    .string()
    .describe('The intended audience for the portfolio (e.g., recruiters, potential clients).'),
});

export type PortfolioReviewInput = z.infer<typeof PortfolioReviewInputSchema>;

const PortfolioReviewOutputSchema = z.object({
  overallFeedback: z.string().describe('Overall feedback on the portfolio.'),
  strengths: z.string().describe('Key strengths of the portfolio.'),
  areasForImprovement: z.string().describe('Areas where the portfolio can be improved.'),
  suggestions: z.string().describe('Specific suggestions for improvement.'),
});

export type PortfolioReviewOutput = z.infer<typeof PortfolioReviewOutputSchema>;

export async function reviewPortfolio(input: PortfolioReviewInput): Promise<PortfolioReviewOutput> {
  return portfolioReviewFlow(input);
}

const portfolioReviewPrompt = ai.definePrompt({
  name: 'portfolioReviewPrompt',
  input: {schema: PortfolioReviewInputSchema},
  output: {schema: PortfolioReviewOutputSchema},
  prompt: `You are an AI-powered portfolio review tool. Your task is to provide personalized feedback and suggestions for improvement on a user's portfolio content.

  Consider the user's goals and target audience when providing feedback.

  Portfolio Content: {{{portfolioContent}}}
  User Goals: {{{userGoals}}}
  Target Audience: {{{targetAudience}}}

  Provide feedback in the following format:
  - Overall Feedback: [Overall assessment of the portfolio]
  - Strengths: [Key strengths of the portfolio]
  - Areas for Improvement: [Areas where the portfolio can be improved]
  - Suggestions: [Specific suggestions for improvement]
  `,
});

const portfolioReviewFlow = ai.defineFlow(
  {
    name: 'portfolioReviewFlow',
    inputSchema: PortfolioReviewInputSchema,
    outputSchema: PortfolioReviewOutputSchema,
  },
  async input => {
    const {output} = await portfolioReviewPrompt(input);
    return output!;
  }
);

